### ISSUE TITLE
weight features

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/rmi-ferc1-eia#10]
once we have a working feature matrix, we need to be able to weight features differently.. maybe we think that capacity really really needs to be close to each other but the fuel cost per mwh doesn't need to be so close. I am currently quite fuzzy on the mechanics of weighting features.. but will figure out in due time. 

we will test various weights of issues in Issue #11, but here we need to create the framework for actually doing the weighting.

**Comment by zaneselvans** [comment]
When you're creating a `scikit-learn` `pipeline` object that does the pre-processing & modelling, there's an option to specify the weights of each of the features you name within the pipeline individually.

**Comment by cmgosnell** [comment]
this is done automatically within the generation of coefficients in a logistic regression model.
