### ISSUE TITLE
testing/cross validation

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/rmi-ferc1-eia#11]
Because our problem fits slightly outside of the normal classification problem, we may need to set up our own testing system. We could determine many permutations of weights for features, develop a scoring method and loop through the options. We could also test various models... we've been thinking about the k-nearest neighbor framework (with n=1) but we could try other options.

**Comment by zaneselvans** [comment]
Depending on how computationally intensive it ends up being, if you end up needing a more efficient way to search around in the parameter space of feature weights, the Neighborhood Algorithm (Sambridge, 1999) is a pretty straightforward and very efficient option. This repo has a Python implementation: https://github.com/keithfma/neighborhood
