### ISSUE TITLE
pull the EIA-depreciation matches out of deprish_raw.xlsx

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/rmi-ferc1-eia#169]
There are two excel tabs that let us add manual overrides/fill in gaps for the matches between the depreciation studies and the EIA plant-part list.

Right now they live in `deprish_raw.xlsx`. Every time we run the depreciation to EIA fuzzy matching process, the outcome of the matches are added back into the "EIA to depreciation matches" tab in `deprish_raw.xlsx`. This way we are always ready to  add or edit the manual matches.

This is problematic because every time we run this process we are getting an update to the excel file, which could blow up the repo's storage overtime.

I see two options here:

1. change the default setting on the depreciation to eia matching process to not export to these tabs!
2. move these tabs to another excel file. They could go in their own matching file. Or they could go in with the common plant labeling. I think a solo file sounds most ideal.

We should probably do both of these things.

**Comment by e-belfer** [comment]
Duplicated in #317 and will be addressed there.
