### ISSUE TITLE
Phase II: Integrate Manually Mapped FERC-EIA Overrides into Training Data

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/rmi-ferc1-eia#176]
This Epic is a continuation of Phase I (#114). It comes after Phase II: Finish Manual Mapping... (#175)

Once we have completed the manual FERC-EIA mapping, we'll want to turn those linkages into training data for the AI algorithm. Once included in the list of training data they will also act as overrides, simultaneously improving the accuracy of the AI output and the AI's ability to make accurate matches.

To run the integration, we'll use the `make_overrides.ipynb` notebook to upload changes to training data. There are instructions in this section that explain what you need to do in order for it to work.

- [x] Duke
- [x] BHE
- [ ] Southern
- [ ] Dominion
- [ ] NextEra
- [ ] Xcel
- [ ] AEP
- [ ] Evergy
- [ ] IdaCorp
- [ ] Entergy

**Comment by e-belfer** [comment]
Closed in #175
