### ISSUE TITLE
formatting test data

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/rmi-ferc1-eia#19]
We need to convert rmi's test data linkages to be in the same format as whatever we feed the matching model.

I think this means we need to do three main things:
- [x] in the compiled dataframes, generate unique record ids in ferc
- [x] in the compiled dataframes, generate unique record ids in eia
- [x] generate those same ids with the test data using the "EIA FERC Line Matching" categorization. this will probably need some prep in the spreadsheet but mostly in pandas

**Comment by zaneselvans** [comment]
I don't know if it's helpful here, but we generate a unique record ID for each FERC record that gets pulled into PUDL (with the exception of the new row-mapped tables like Plant in Service) that has the format: `{table_name}_{report_year}_{report_prd}_{respondent_id}_{spplmnt_num}_{row_number}`
