### ISSUE TITLE
convert hub's EIA inputs to PUDL

### ISSUE THREAD

**Issue by cmgosnell** [catalyst-cooperative/rmi-ferc1-eia#200]
The Hub team has been using their own EIA process to generate their "owned_generators" output. This happened because they needed older years faster we were able to integrate them. But we have them integrated now! So the task here is to strip the old processing that is no longer needed and convert directly to `pudl_out` inputs.

I can assume folks have a pudl sqlite db downloaded in `PUDL_OUT` and have pudl installed.

Questions:
- It seems like you've been using the output from `pudl.analysis.allocate_net_gen.allocate_gen_fuel_by_gen_pm_fuel` which generates allocated net generation for each generator/prime_mover/fuel record. This is *not* the standard output that we are currently using in the EIA plant-parts table (or rather the generator-input `pudl.plant_parts_eia.MakeMegaGenTbl()`)... Is this happening because you want to be able to calculate the emissions factor by fuel-type before it gets aggregated? This is probably a question for @jrea-rmi 

Notes:
We'll probably need to use or repurpose this chunk of `create_eia_generators`:
```
.pipe(calculate_potential_gen)
.merge(emissions_factors, on="fuel_type_code", how="left")
.pipe(estimate_emissions_from_fuel)
.pipe(add_nox_sox, epa_emissions)
```

**Comment by jrea-rmi** [comment]
> The Hub team has been using their own EIA process to generate their "owned_generators" output. This happened because they needed older years faster we were able to integrate them. But we have them integrated now! So the task here is to strip the old processing that is no longer needed and convert directly to `pudl_out` inputs.
> 
> I can assume folks have a pudl sqlite db downloaded in `PUDL_OUT` and have pudl installed.
> 
> Questions:
> 
> * It seems like you've been using the output from `pudl.analysis.allocate_net_gen.allocate_gen_fuel_by_gen_pm_fuel` which generates allocated net generation for each generator/prime_mover/fuel record. This is _not_ the standard output that we are currently using in the EIA plant-parts table (or rather the generator-input `pudl.plant_parts_eia.MakeMegaGenTbl()`)... Is this happening because you want to be able to calculate the emissions factor by fuel-type before it gets aggregated? This is probably a question for @jrea-rmi
> 
> Notes: We'll probably need to use or repurpose this chunk of `create_eia_generators`:
> 
> ```
> .pipe(calculate_potential_gen)
> .merge(emissions_factors, on="fuel_type_code", how="left")
> .pipe(estimate_emissions_from_fuel)
> .pipe(add_nox_sox, epa_emissions)
> ```

yes, I believe that's correct. We want generation and fuel consumption by fuel type within each generator. This is useful for the current emissions estimate using emissions factors, but also allows us to determine generation by fuel rather than just by technology. Does that mean we won't use the plant-parts table?

**Comment by cmgosnell** [comment]
Okay, great. Thanks for this. This makes this a little less simple than `owned_generators = pudl_out.gens_mega()`... but I think we will still be able to use the code that we currently use to generate the "owned" records with the data columns scaled to the fraction owned.

**Comment by cmgosnell** [comment]
okay... I made a [draft PR](https://github.com/catalyst-cooperative/pudl/pull/1575) over in pudl that will hopefully make main something like this:

```
def main():
    """
    Executes the module from start to finish, exporting versions of owned_generators.csv to data_inputs/synthesized
    """
    # instantiate the pudl_out object
    pudl_out = pudl.output.pudltabl.PudlTabl(
        c.pudl_engine,
        freq="AS",
        fill_fuel_cost=True,
        roll_fuel_cost=True,
        fill_net_gen=True,
    )

    gen_pm_fuel_own = pudl_out.gen_pm_fuel_ownership()
    owned_generators = (
        gen_pm_fuel_own[gen_pm_fuel_own.ownership == "owned"]
        .pipe(calculate_potential_gen)
        .merge(emissions_factors, on="energy_source_code", how="left")
        .pipe(estimate_emissions_from_fuel)
        .pipe(add_nox_sox, create_epa_emissions())
    )

    export_owned_generators(owned_generators)

    return owned_generators
```

I had to change a  few things in the emissions functions but nothing major. One more question for @jrea-rmi ... we discussed **not** converting the column names back to what y'all had (aka abandoning the `rename_cols_to_rmi`). Is this going to have any downstream effects that I should be aware of or help clean up??

**Comment by jrea-rmi** [comment]
We want rename_cols_to_rmi somewhere, and I think it would live in owned_generators.py. But would happen at the very end, after everything that uses pudl.
