### ISSUE TITLE
Write tests for FERC-EIA training data validation and spreadsheet creation

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/rmi-ferc1-eia#314]
Create integration tests for the validation of the training data as well as the creation of the override spreadsheets housed in `pudl.analysis.ferc1_eia_train.py`

**Comment by e-belfer** [comment]
Addressed in [PR #2347](https://github.com/catalyst-cooperative/pudl/pull/2347) in the pudl repo.

**Comment by e-belfer** [comment]
Closed in [PR #2502](https://github.com/catalyst-cooperative/pudl/pull/2502)
